### PR TITLE
Adjustments and additions for responsive home page graphic, refs #9392

### PR DESCRIPTION
**Pull request by mtribone**
Made some adjustments and additions to the SCSS files and a slight change to a view for a better responsive design and added background images to target certain breakpoints. Images can be replaced in the future if needed.

### CODE REVIEW

**Comment by carolyncole** [comment]
:+1: Looks Good to me.  @awead any comments?

**Comment by awead** [comment]
Very nice.  My only thought, iPhone is 320 ppi in portrait mode (480 in landscape).  Is that an issue?

**Comment by mtribone** [comment]
@awead I can squeeze another media query in there and see what our stats look like over the next several months.

**Comment by carolyncole** [comment]
I'm merging it and we can tweak later if need be...

**Pull request merged**
