### PR TITLE
Rename buttons in create collection page, ref #590

### PR DESCRIPTION
**Pull request by awead**
When creating a new collection, three different buttons will appear:
* creating a new, empty collection
* creating a new collection, then redirecting to the batch create page with the newly created collection pre-selected so that you may add new works to the collection.
* creating a new collection, then redirecting to the dashboard works page so that you can select existing works to add to the new collection.

new

Additionally, when doing the reverse of option 3 above, and selecting works from the dashboard first, then creating a new collection, only one button is shown. Also, a listing of the works that will be added to the collection is displayed using the same UI components that are used when displaying works in existing collections.

existing

Note: also includes some refactoring of the collection feature tests, separating create and delete tests.

### CODE REVIEW

**Review by mtribone — COMMENTED** [review]
We have 3 buttons with the same ID `create_submit`. I'm guessing that it is for the JS?

**Comment by awead** [comment]
@mtribone I'm not really sure. From what I can tell, the id isn't really used for anything. I'm happy to use different ids. Does this impact accessibility?

**Comment by mtribone** [comment]
@awead I don't think that it will affect accessibility if the ID isn't being used for anything. It's a best practice to have only one ID with the same name on a page, but I wasn't sure if there was any JS using that ID when the button is clicked. For example, if `create_submit` kicks off any other processes. Not a blocker.

**Comment by awead** [comment]
@mtribone the id isn't being used for anything, but I agree, probably better to use different ids. Let me update it.

**Pull request merged**
