### PR TITLE
Make the Batch Upload Link More Apparent

### PR DESCRIPTION
**Pull request by mtribone**
Uses some JS to override and insert styles without overriding a template for a simple thing. Not super design sexy, but it works.

screen shot 2017-03-09 at 1 16 56 pm

### CODE REVIEW

**Comment by awead** [comment]
@mtribone interesting. I would have just overridden the view. Too much?

**Comment by mtribone** [comment]
@awead If I do, I'll need to make note of it. Overriding for a class name has come up in the past. Go for it?

**Comment by awead** [comment]
@mtribone meh. I'm good with this if you are. Could you put a comment in the layout.js to explain why it's there?

**Comment by mtribone** [comment]
@awead I'm adding the overrides. :-)

**Comment by mtribone** [comment]
screen shot 2017-03-09 at 1 58 22 pm

**Comment by mtribone** [comment]
Overrides both screens to go back and forth between batch and single work.

**Pull request merged**
