### PR TITLE
updated sufia version

### PR DESCRIPTION
**Pull request by bmaddy**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Looks clean to me.  :+1:

**Comment by bmaddy** [comment]
I just resolved the merge conflict. This should also fix the failing build on develop.

**Comment by bmaddy** [comment]
```
  1) Dashboard Files with one file: interactions are wired correctly
     Failure/Error: page.should have_content 'Visibility'
       expected to find text "Visibility" in "ScholarSphere Joe Example Home About Help Contact Search
Sufia Go All Home / Files / little_file.txt Edit little_file.txt <<Browse view Descriptions Versions 
Permissions Descriptions * indicates required fields Resource type You may select multiple types to 
apply Title +add another title Creator +add another creator Contributor +add another contributor 
Description +add another description Keyword +add another tag Rights +add another rights Publisher 
+add another publisher Date Created +add another date_created Subject +add another subject 
Language +add another language Identifier +add another identifier Location +add another based_near 
Related URL +add another related_url Save Descriptions ScholarSphere v1.10 A service of the 
University Libraries and Information Technology Services. Copyright © 2012 The Pennsylvania State 
University Penn State | University Libraries | Information Technology Services | Accessibility"
```

```
spec/features/dashboard/dashboard_files_spec.rb:20
```

This error is showing up on the develop branch also (it was just hidden by the css selector error that this PR fixes). @awead, do you know anything about this? It looks like you were doing something with Visibility on sufia recently.

**Comment by awead** [comment]
@bmaddy yes, projecthydra/sufia#616 fixes this

**Pull request merged**
