### PR TITLE
Make the collection icon color consistent throughout the system

### PR DESCRIPTION
**Pull request by mtribone**
Replaces the color of the collection png and switches the fa-cubes font icon to blue.

### CODE REVIEW

**Comment by mtribone** [comment]
screen shot 2016-10-25 at 8 57 20 pm

**Comment by mtribone** [comment]
screen shot 2016-10-25 at 8 56 49 pm

**Comment by mtribone** [comment]
screen shot 2016-10-25 at 8 56 30 pm

**Comment by mtribone** [comment]
screen shot 2016-10-25 at 8 55 44 pm

**Comment by carolyncole** [comment]
Looks good!  Waiting on Travis

**Comment by mtribone** [comment]
@cam156 just rebased with develop even though it wasn't needed. just in that flow

**Pull request merged**
