### PR TITLE
Comments out the link to the admin stats from the dashboard

### LINKED ISSUE #1246: Admin stats is broken
the admin stats page is broken, when logged in and clicking on the link for the statistics I get an error page
https://scholarsphere.psu.edu/admin/stats

screen shot 2018-05-18 at 9 25 04 am

### PR DESCRIPTION
**Pull request by mtribone**
I've decided to comment out the code that links to the admin stats in the dashboard from the greeting instead of remove it completely, so that we can uncomment it out when the code has been fixed.

Fixes #1246

### CODE REVIEW

**Review by awead — COMMENTED** [review]
@mtribone Why not just remove the lines?

**Comment by mtribone** [comment]
@awead Yeah I went back and forth about deleting them and thought it _might_ be useful later? I can remove them if it's just clutter.

**Comment by awead** [comment]
@mtribone I'm always a fan of removing code as opposed to just commenting it out, unless we want to re-enable it later.

**Comment by mtribone** [comment]
@awead I've removed it. It won't be too hard to find and add later once #1175 is fixed.

**Review by awead — APPROVED** [review]

**Pull request merged**
