### PR TITLE
Speed up Travis by using bundle caching and container architecture

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Why is the passenger commit included in the PR?

**Comment by mjgiarlo** [comment]
Or is this a bogus branch now?  I don't see bundler caching in the travis config anymore.

**Comment by mjgiarlo** [comment]
Btw, the failure above is actually a lie.  Click the link for proof.  Ready to merge?

Build finished in just a little over 10m!

**Comment by awead** [comment]
Weird. Why is it showing failed in the first place?

**Comment by mjgiarlo** [comment]
It failed on the first run four weeks ago. :)  Then I re-ran the build when I saw this PR waiting here and presto.  Dunno why GitHub didn't update this page.

**Pull request merged**
