### PR TITLE
Moving the help to the top of the page and changing the cloud wording

### PR DESCRIPTION
**Pull request by carolyncole**
refs #601
screen shot 2017-03-01 at 9 51 31 am

### CODE REVIEW

**Comment by carolyncole** [comment]
@mtribone @olendorf what do you think?

**Comment by mtribone** [comment]
@cam156 I think that the header for cloud files is much more readable now. I wonder if people will actually read the help text, but that is for users to tell us. Part of me wonders if the button should also be "+ Add files" for consistency. Add versus browse seems more active to me, but not a blocker.

**Comment by carolyncole** [comment]
@mtribone how about "+ Add Cloud Files" to make the buttons read differently?

**Comment by carolyncole** [comment]
@mtribone adding the + is particularly tricky for the browse everything button.  Would just removing it from all work?

screen shot 2017-03-03 at 10 57 34 am

**Comment by mtribone** [comment]
The more that we can remove items that do not add or increase the meaning of something in the UI, the better the interface will be for users.

**Comment by carolyncole** [comment]
@awead & @mtribone this should be all set now.

**Pull request merged**
