### PR TITLE
Audio Icon

### PR DESCRIPTION
**Pull request by mtribone**
Replaces Sufia's default folder with musical notes icon with the volume icon.

### CODE REVIEW

**Comment by mtribone** [comment]
screen shot 2016-10-26 at 1 37 44 pm

**Comment by mtribone** [comment]
screen shot 2016-10-26 at 1 38 35 pm

**Comment by carolyncole** [comment]
@mtribone what does it look like in all the catalog views?

**Comment by mtribone** [comment]
screen shot 2016-10-27 at 8 43 42 am

**Comment by mtribone** [comment]
screen shot 2016-10-27 at 8 45 18 am

**Pull request merged**
