### PR TITLE
Test automation static pages

### PR DESCRIPTION
**Pull request by cswalina**
@cam156 

Here is a feature test ( refs issue #11 ) for "Test Automation Static Pages".

Assuming it meets your approval, how do you want us to add it to the develop branch? We were thinking that the cleanest way to do it would be to save the spec file, eliminate this branch, and then add the spec file to develop with a single commit (rather than merging in all of our scratch work commits in this branch). Does that sound like a good approach?

### CODE REVIEW

**Comment by mjgiarlo** [comment]
An alternative approach that we use quite often in the Hydra project would be for you to squash your commits on this branch then force-push back to the same branch. (That way, up above it will say there's 1 commit rather than 11 commits.) Notes on that here: http://ndlib.github.io/practices/one-commit-per-pull-request/

Once you do that, this pull request will be automatically updated.  Once that's done and Travis comes back with good news, any of us can merge it.  Thanks!

**Comment by cswalina** [comment]
Thanks Mike. We squashed and force pushed, but one of our new specs fails on Travis (all tests pass locally though). We'll have to dig into what's going on on Travis ...

**Comment by mjgiarlo** [comment]
Weird.  I have no idea why adding a spec would cause a failure in the proxy spec.  Good luck tracking that down!

**Comment by woods** [comment]
@cam156 

We need some help: this test is complete and passes individually, but the build fails intermittently on Travis. We're not having any luck tracking down what could be causing the failures elsewhere in the suite. 

We suspect that it's because of an incomplete setup/teardown somewhere that's causing the test ordering to become significant, but we don't have enough background knowledge to track this down efficiently.

Whenever it's convenient, can someone please do the following for us:
1. Take a quick look at our changes to make sure we're not missing a set up or tear down step that could be causing state problems.
2. Check out the branch and verify that the test passes for you.
3. See if you can provide any insight on why other tests intermittently fail on Travis when we introduced this test.

In the meantime, we're working on other branches, so this isn't exactly holding us up, but we can't complete it without some additional insight, if nothing else to confirm that we're not missing anything and it would be time well spent for us to investigate further.

Thanks!

**Comment by mjgiarlo** [comment]
I'll take a quick look, @woods.

**Comment by woods** [comment]
Thanks!

On Tue, Mar 11, 2014 at 5:42 PM, Michael J. Giarlo <notifications@github.com

> wrote:
> 
> I'll take a quick look, @woods https://github.com/woods.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/psu-stewardship/scholarsphere/pull/16#issuecomment-37352752
> .

## 

Scott Woods
West Arete
http://westarete.com/
scott@westarete.com
814-753-4951

**Comment by mjgiarlo** [comment]
And then GitHub went down.  Now that it's back, I'll take a quick look. :smile:

**Comment by mjgiarlo** [comment]
I can't get that particular test to fail, but I do get a failure unrelated to your changes (and possibly related to setup/teardown). Going to troubleshoot this a bit, @woods.

**Comment by mjgiarlo** [comment]
I pushed a commit to this branch with one minor change.  I'm not confident that it fixes anything but my tests pass now, FWIW.

**Comment by mjgiarlo** [comment]
Well, that run passed anyway.  I think this is good to merge.  Thanks, y'all!

:clap:

**Comment by woods** [comment]
Thank you so much, Mike!

On Tue, Mar 11, 2014 at 8:03 PM, Michael J. Giarlo <notifications@github.com

> wrote:
> 
> Merged #16 https://github.com/psu-stewardship/scholarsphere/pull/16.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/psu-stewardship/scholarsphere/pull/16
> .

## 

Scott Woods
West Arete
http://westarete.com/
scott@westarete.com
814-753-4951

**Pull request merged**
