### PR TITLE
Upgrade gems

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:watch: on Travis

**Comment by mjgiarlo** [comment]
:disappointed:

**Comment by mjgiarlo** [comment]
:watch: :watch: :watch:

**Comment by carolyncole** [comment]
@jcoyne Foo!  I merged Valerie's, which conflicts with yours.  Can you rebase?

**Comment by jcoyne** [comment]
@cam156 rebased

**Pull request merged**
