### PR TITLE
Adding ReCAPTCHA to email form to stop spam

### PR DESCRIPTION
**Pull request by awead**
Uses Google's ReCAPTCHA service to stop spam from getting through via our contact form.

Configuration of the service is documented here: http://sites.psu.edu/dltdocs/?p=4084
And the server configs have been updated, as noted in: http://sites.psu.edu/dltdocs/?p=3521

This has been tested in QA, but still requires some UI work and accessibility verification.
recaptcha

### CODE REVIEW

**Comment by mtribone** [comment]
screen shot 2018-03-13 at 12 48 53 pm

**Review by carolyncole — COMMENTED** [review]
@awead I am guessing the drop in coverage is due to the copying in of the contact form. I would believe our feature test is not covering the entire form.  Maybe you could double check that test to be certain.

**Comment by awead** [comment]
@cam156 reading the report in coveralls https://coveralls.io/builds/15954289, "New Missed Lines in Diff" is saying `lib/scholarsphere/config.rb` dropped by 36%. `app/controllers/contact_form_controller.rb` is at 100%. Is that a correct reading?

**Comment by carolyncole** [comment]
@awead I think coveralls has changed and is now truly confused by our two builds.  I'm just going to merge this.

**Pull request merged**
